import { Inter } from "next/font/google";
import "@styles/globals.css";
import { ThemeProvider } from "@components/theme-provider";
import { Toaster } from "react-hot-toast";
import Header from "@components/header";

import Provider from "@components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Provider>
            <div className="bg-wrapper">
              <div className="gradient"></div>
            </div>
            <main className="relative z-10 flex justify-center items-center flex-col max-w-7xl mx-auto sm:px-16 px-6">
              <Header />
              {children}
            </main>
            <Toaster />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
